#!/usr/bin/env bash
# Author: "abpwrs"
# Date: 20190326

if [ $# -ne 1 ]; then
  echo "... Incorrect Usage ..."
  echo "Usage: ${0} ProjectNameNoSpaces"
  exit -1
fi

DATE=$(date +%Y%m%d)
PROJECT_NAME=${1}
DIR_NAME="${DATE}_${PROJECT_NAME}"
mkdir ${DIR_NAME}
